trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-20.04'
    continueOnError: false
    steps:
    - script: echo "hello to my first script test Build ubuntu 20.04"
- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev deploy world with ubuntu latest!!!"
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: 'Ubuntu-22.04'
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa deploy world using ubuntu 22.04!!!"